# LABORATÓRIO 4 — Business Intelligence e Data Warehousing

Disciplina: Gestão de Sistemas de Informação  
Professor: Eduardo Max Amaro Amaral  

## Objetivo

Simular o ciclo completo de um Data Warehouse (DW) por meio de um processo ETL (Extract, Transform, Load), integrando sistemas isolados e gerando uma "Verdade Única" organizacional.

# Contexto do Problema

A organização possui dois sistemas isolados:

- Sistema de Vendas → contém apenas SKU e quantidade vendida.
- Sistema de Produtos → contém SKU, nome e preço.

Nenhum dos sistemas, isoladamente, permite calcular o faturamento.

Este cenário caracteriza **Ilhas de Dados**.

In [6]:
import pandas as pd

print("ETAPA 1 - EXTRAÇÃO")

vendas = pd.read_csv("vendas.csv")
produtos = pd.read_csv("produtos.csv")

print("\nTabela Vendas:")
display(vendas.head())

print("\nTabela Produtos:")
display(produtos.head())

ETAPA 1 - EXTRAÇÃO

Tabela Vendas:

    sku  qtd
0  P044   15
1  P010   20
2  P074    9
3  P076   12
4  P001   10

Tabela Produtos:

    sku      nome  preco
0  P001    Webcam    795
1  P002  Mousepad    549
2  P003     Mouse   2226
3  P004   Teclado   2414
4  P005  Mousepad   2267

## Interoperabilidade Técnica

Nesta etapa ocorre interoperabilidade técnica, pois arquivos CSV heterogêneos são lidos e interpretados por uma ferramenta comum (Python/Pandas).

In [7]:
print("ETAPA 2 - TRANSFORMAÇÃO")

dw = pd.merge(vendas, produtos, on="sku")

print("\nTabela após Merge:")
display(dw.head())

ETAPA 2 - TRANSFORMAÇÃO

Tabela após Merge:

    sku  qtd     nome  preco
0  P044   15    Mouse    634
1  P010   20   Webcam    906
2  P074    9  Monitor   1972
3  P076   12  Headset   2870
4  P001   10   Webcam    795

## Interoperabilidade Semântica

O SKU atua como elo semântico entre os sistemas.

Sem um SKU padronizado, não seria possível associar corretamente quantidade e preço.

In [8]:
dw["faturamento"] = dw["qtd"] * dw["preco"]

print("\nTabela com Faturamento:")
display(dw.head())

Tabela com Faturamento:

    sku  qtd     nome  preco  faturamento
0  P044   15    Mouse    634         9510
1  P010   20   Webcam    906        18120
2  P074    9  Monitor   1972        17748
3  P076   12  Headset   2870        34440
4  P001   10   Webcam    795         7950

In [9]:
dw["nome"] = dw["nome"].str.upper()

print("\nTabela após Padronização:")
display(dw.head())

Tabela após Padronização:

    sku  qtd     nome  preco  faturamento
0  P044   15    MOUSE    634         9510
1  P010   20   WEBCAM    906        18120
2  P074    9  MONITOR   1972        17748
3  P076   12  HEADSET   2870        34440
4  P001   10   WEBCAM    795         7950

In [10]:
dw.to_csv("data_warehouse_final.csv", index=False)

print("Data Warehouse salvo com sucesso!")

Data Warehouse salvo com sucesso!

# Conclusão

O processo ETL permitiu:

- Integrar silos organizacionais
- Aplicar regras de negócio centralizadas
- Garantir governança de dados
- Criar uma fonte única de verdade

O Data Warehouse consolidado permite análises estratégicas e decisões baseadas em dados.